In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [12]:
train = pd.read_csv("/kaggle/input/competitions/triagegeist/train.csv")
test = pd.read_csv("/kaggle/input/competitions/triagegeist/train.csv")

train.head()

,patient_id,site_id,triage_nurse_id,arrival_mode,arrival_hour,arrival_day,arrival_month,arrival_season,shift,age,...,gcs_total,pain_score,weight_kg,height_cm,bmi,shock_index,news2_score,disposition,ed_los_hours,triage_acuity
0,TG-UXRGA9UCO,SITE-TMP-01,NURSE-0033,walk-in,6,Monday,5,spring,morning,43,...,14,7,52.3,165.4,19.1,0.725,8,discharged,7.35,2
1,TG-B19DBBS2G,SITE-HEL-01,NURSE-0001,walk-in,6,Thursday,4,spring,morning,72,...,15,-1,73.3,164.4,27.1,0.739,1,discharged,0.70,5
2,TG-GZ97W7M6V,SITE-HEL-02,NURSE-0005,walk-in,8,Saturday,4,spring,morning,82,...,15,3,77.1,183.7,22.8,0.798,2,discharged,0.63,5
3,TG-THIB2TN9Q,SITE-HEL-02,NURSE-0026,police,7,Sunday,3,spring,morning,50,...,15,7,49.6,172.6,16.6,0.812,2,discharged,1.99,3
4,TG-J3U3LQ2QY,SITE-HEL-02,NURSE-0044,walk-in,5,Tuesday,5,spring,night,62,...,15,4,71.9,173.4,23.9,0.812,2,transferred,3.58,3

In [13]:
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                80000 non-null  object
 1   site_id                   80000 non-null  object
 2   triage_nurse_id           80000 non-null  object
 3   arrival_mode              80000 non-null  object
 4   arrival_hour              80000 non-null  int64
 5   arrival_day               80000 non-null  object
 6   arrival_month             80000 non-null  int64
 7   arrival_season            80000 non-null  object
 8   shift                     80000 non-null  object
 9   age                       80000 non-null  int64
 10  age_group                 80000 non-null  object
 11  sex                       80000 non-null  object
 12  language                  80000 non-null  object
 13  insurance_type            80000 non-null  object
 14  transport_origin          80000 non-null  object
 15  pain_location             80000 non-null  object
 16  mental_status_triage      80000 non-null  object
 17  chief_complaint_system    80000 non-null  object
 18  num_prior_ed_visits_12m   80000 non-null  int64
 19  num_prior_admissions_12m  80000 non-null  int64
 20  num_active_medications    80000 non-null  int64
 21  num_comorbidities         80000 non-null  int64
 22  systolic_bp               75854 non-null  float64
 23  diastolic_bp              75854 non-null  float64
 24  mean_arterial_pressure    75854 non-null  float64
 25  pulse_pressure            75854 non-null  float64
 26  heart_rate                80000 non-null  float64
 27  respiratory_rate          76933 non-null  float64
 28  temperature_c             79426 non-null  float64
 29  spo2                      80000 non-null  float64
 30  gcs_total                 80000 non-null  int64
 31  pain_score                80000 non-null  int64
 32  weight_kg                 80000 non-null  float64
 33  height_cm                 80000 non-null  float64
 34  bmi                       80000 non-null  float64
 35  shock_index               75854 non-null  float64
 36  news2_score               80000 non-null  int64
 37  disposition               80000 non-null  object
 38  ed_los_hours              80000 non-null  float64
 39  triage_acuity             80000 non-null  int64
dtypes: float64(13), int64(11), object(16)
memory usage: 24.4+ MB

,arrival_hour,arrival_month,age,num_prior_ed_visits_12m,num_prior_admissions_12m,num_active_medications,num_comorbidities,systolic_bp,diastolic_bp,mean_arterial_pressure,...,spo2,gcs_total,pain_score,weight_kg,height_cm,bmi,shock_index,news2_score,ed_los_hours,triage_acuity
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,75854.000000,75854.000000,75854.000000,...,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,75854.000000,80000.000000,80000.000000,80000.000000
mean,11.430600,6.507413,48.544225,1.378162,0.414700,4.791425,5.348838,121.612599,74.452339,90.172434,...,95.793801,14.152125,4.505975,74.453355,168.623680,26.359772,0.810019,3.426825,3.498276,3.324162
std,6.923497,3.457444,24.187528,1.429609,0.773535,3.858404,3.187295,24.221898,14.285613,14.174033,...,4.306756,2.145761,3.359763,21.339829,16.592256,7.666452,0.327007,4.258565,2.443958,1.040034
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,40.000000,20.000000,30.700000,...,60.400000,3.000000,-1.000000,2.000000,45.000000,10.000000,0.190000,0.000000,0.000000,1.000000
25%,5.000000,3.000000,29.000000,0.000000,0.000000,2.000000,3.000000,106.200000,65.500000,81.900000,...,94.100000,15.000000,2.000000,62.000000,163.400000,21.300000,0.601000,0.000000,1.580000,3.000000
50%,11.000000,7.000000,48.000000,1.000000,0.000000,4.000000,5.000000,123.100000,75.300000,91.900000,...,97.000000,15.000000,5.000000,76.000000,171.100000,26.000000,0.724000,2.000000,3.000000,3.000000
75%,17.000000,10.000000,67.000000,2.000000,1.000000,7.000000,8.000000,138.300000,84.200000,100.000000,...,98.900000,15.000000,7.000000,88.800000,178.100000,30.900000,0.920000,5.000000,4.860000,4.000000
max,23.000000,12.000000,94.000000,11.000000,9.000000,20.000000,20.000000,226.900000,134.800000,145.100000,...,100.000000,15.000000,10.000000,148.500000,210.000000,65.000000,4.768000,17.000000,17.510000,5.000000

In [14]:
train.isnull().sum()

patient_id                     0
site_id                        0
triage_nurse_id                0
arrival_mode                   0
arrival_hour                   0
arrival_day                    0
arrival_month                  0
arrival_season                 0
shift                          0
age                            0
age_group                      0
sex                            0
language                       0
insurance_type                 0
transport_origin               0
pain_location                  0
mental_status_triage           0
chief_complaint_system         0
num_prior_ed_visits_12m        0
num_prior_admissions_12m       0
num_active_medications         0
num_comorbidities              0
systolic_bp                 4146
diastolic_bp                4146
mean_arterial_pressure      4146
pulse_pressure              4146
heart_rate                     0
respiratory_rate            3067
temperature_c                574
spo2                           0
gcs_total                      0
pain_score                     0
weight_kg                      0
height_cm                      0
bmi                            0
shock_index                 4146
news2_score                    0
disposition                    0
ed_los_hours                   0
triage_acuity                  0
dtype: int64

In [15]:
train = train.fillna(train.median(numeric_only=True))

In [16]:
train.isnull().sum()

patient_id                  0
site_id                     0
triage_nurse_id             0
arrival_mode                0
arrival_hour                0
arrival_day                 0
arrival_month               0
arrival_season              0
shift                       0
age                         0
age_group                   0
sex                         0
language                    0
insurance_type              0
transport_origin            0
pain_location               0
mental_status_triage        0
chief_complaint_system      0
num_prior_ed_visits_12m     0
num_prior_admissions_12m    0
num_active_medications      0
num_comorbidities           0
systolic_bp                 0
diastolic_bp                0
mean_arterial_pressure      0
pulse_pressure              0
heart_rate                  0
respiratory_rate            0
temperature_c               0
spo2                        0
gcs_total                   0
pain_score                  0
weight_kg                   0
height_cm                   0
bmi                         0
shock_index                 0
news2_score                 0
disposition                 0
ed_los_hours                0
triage_acuity               0
dtype: int64

In [17]:
train['triage_acuity'].value_counts()

triage_acuity
3    28921
4    23020
2    13439
5    11398
1     3222
Name: count, dtype: int64

In [18]:
X = train.drop("triage_acuity", axis=1)
y = train["triage_acuity"]

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'TG-BHMV73Q95'

In [ ]:
X.dtypes

In [ ]:
X = pd.get_dummies(X)

In [ ]:
X.dtypes

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

In [ ]:
test = pd.read_csv("/kaggle/input/competitions/triagegeist/test.csv")

test = test.fillna(test.median(numeric_only=True))

test = pd.get_dummies(test)

In [ ]:
test = test.reindex(columns=X.columns, fill_value=0)

In [ ]:
accuracy = model.score(X_val, y_val)
print("Validation Accuracy:", accuracy)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model = RandomForestClassifier()


model.fit(X_train, y_train)

In [ ]:
X.columns

In [ ]:
X = train.drop(["triage_acuity", "patient_id"], axis=1)
y = train["triage_acuity"]

In [ ]:
X = pd.get_dummies(X)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier()

model.fit(X_train, y_train)

In [ ]:
accuracy = model.score(X_val, y_val)

print("Validation Accuracy:", accuracy)

In [ ]:
test = pd.read_csv("/kaggle/input/competitions/triagegeist/test.csv")

test_ids = test["patient_id"]

test = test.drop("patient_id", axis=1)

test = test.fillna(test.median(numeric_only=True))

test = pd.get_dummies(test)

test = test.reindex(columns=X.columns, fill_value=0)

In [ ]:
predictions = model.predict(test)

In [ ]:
submission = pd.DataFrame({
    "patient_id": test_ids,
    "triage_acuity": predictions
})

submission.to_csv("submission.csv", index=False)

In [ ]:
submission.to_csv("submission.csv", index=False)